import Head from 'next/head';
import StyledComponentsRegistry from './_utilities/antd_registry';
import ConfigProvider from 'antd/es/config-provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StyledComponentsRegistry>
      <ConfigProvider>
        <html lang="en">
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <body>{children}</body>
        </html>
      </ConfigProvider>
    </StyledComponentsRegistry>
  )
}
